### ISSUE TITLE
Type errors on new major version → 11.0.2

### ISSUE THREAD

**Issue by philcockfield** [unifiedjs/unified#228] opened 2023-08-21 01:58 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified@11.0.2, remark-parse@10.0.2

### Link to runnable example

https://github.com/philcockfield/unified-type-error

### Steps to reproduce

The sample repo above is a vanilla typescript setup with `unified@11.0.2` and `remark-parse` added to show typescript type error.

The first 2 lines of the "getting started" sample on the Unified README are used to demonstrate the type error below, although other plugins that were successfully being used with the prior major version of unified@10.1.2 also produce similar type errors:

```
import { unified } from "unified";
import remarkParse from "remark-parse";

unified().use(remarkParse);
```

producing type error:

```
src/index.ts:4:15 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(preset?: Preset | null | undefined): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Type 'Plugin<[(Options | undefined)?], string, Root>' has no properties in common with type 'Preset'.
```

### Expected behavior

Strongly typed as prior version (?? →  I could not find any updated mentions in the unified README to setup types specially)

### Actual behavior

The type error occurs at initial configuration of the pipeline:

<img width="1212" alt="image" src="https://github.com/unifiedjs/unified/assets/185555/e13060db-15a7-4adc-8a9e-4e9a3bc891a5">

### Affected runtime and version

node@19

### Affected package manager and version

npm@9.6.3

### Affected OS and version

MacOS 13.4.1

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment] 2023-08-21 02:06
Duplicate of https://github.com/unifiedjs/unified/issues/227

**Closed by ChristianMurphy** 2023-08-21 02:06 UTC
Labels: 🤞 phase/open

**Comment by ChristianMurphy** [comment] 2023-08-21 02:10
The ecosystem is in the process of being updated.
Hold on unified version 10 major until remark is updated.

**Comment by philcockfield** [comment] 2023-08-21 06:31
Awesome - thanks guys.  I'll sit tight!  
Appreciate your beautiful work.
