### ISSUE TITLE
TypeScript error when doing simple unified markdown pipeline

### ISSUE THREAD

**Issue by pudo** [unifiedjs/unified#229] opened 2023-08-25 09:37 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unified 11.0

### Link to runnable example

https://github.com/opensanctions/site/blob/main/lib/util.tsx#L11-L20

### Steps to reproduce

I'm trying to just build a string of markdown into some HTML using TypeScript and unified. When attempting to upgrade from unified 10 to 11, the very simple call syntax present in the README file of this project is rejected because of type inconsistencies. All the other dependencies are up to date, so I'm a curious if there may be a need to updated the usage as per `README`? 

### Expected behavior

The same pipeline works flawlessly using unified 10.

### Actual behavior

```
./lib/util.tsx:13:10
Type error: No overload matches this call.
  Overload 1 of 3, '(preset?: Preset | null | undefined): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Type 'Plugin<[(Options | undefined)?], string, Root>' has no properties in common with type 'Preset'.
  Overload 2 of 3, '(list: PluggableList): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Argument of type 'Plugin<[(Options | undefined)?], string, Root>' is not assignable to parameter of type 'PluggableList'.
  Overload 3 of 3, '(plugin: Plugin<[], undefined, undefined>, ...parameters: [] | [boolean]): Processor<undefined, undefined, undefined, undefined, undefined>', gave the following error.
    Argument of type 'Plugin<[(Options | undefined)?], string, Root>' is not assignable to parameter of type 'Plugin<[], undefined, undefined>'.
      The 'this' types of each signature are incompatible.
        Type 'Processor<undefined, undefined, undefined, undefined, undefined>' is not assignable to type 'Processor<Root, Root, void, void>'.
          Types of property 'use' are incompatible.
            Type '{ <Parameters_2 extends unknown[] = [], Input extends string | Node | undefined = undefined, Output = Input>(preset?: Preset | null | undefined): Processor<undefined, undefined, undefined, undefined, undefined>; <Parameters_2 extends unknown[] = [], Input extends string | ... 1 more ... | undefined = undefined, Outp...' is not assignable to type '{ <PluginParameters extends any[] = any[], Input = Root, Output = Input>(plugin: Plugin<PluginParameters, Input, Output>, ...settings: [boolean] | PluginParameters): UsePlugin<...>; <PluginParameters extends any[] = any[], Input = Root, Output = Input>(tuple: [...] | [...]): UsePlugin<...>; (presetOrList: Preset | P...'.
              Types of parameters 'preset' and 'plugin' are incompatible.
                Type 'Plugin<any, any, any>' has no properties in common with type 'Preset'.

  11 | export function markdownToHtml(markdown: string): string {
  12 |   const result = unified()
> 13 |     .use(remarkParse)
     |          ^
  14 |     .use(remarkRehype, { allowDangerousHtml: true })
  15 |     .use(rehypeRaw)
  16 |     .use(rehypeHighlight)
```

### Affected runtime and version

node@20.4.0

### Affected package manager and version

9.7.2

### Build and bundle tools

Next.js

**Comment by remcohaszing** [comment] 2023-08-25 10:16
Duplicate of https://github.com/unifiedjs/unified/issues/227

**Closed by remcohaszing** 2023-08-25 10:16 UTC
Labels: 🤞 phase/open
